name: depmod github action 流程测试
on: [push]
jobs:
  check-mod-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - run: go install github.com/tangtj/depmod@master
      # config.json 可以从其他地方弄过来
      - run: depmod -c config-pass.json -m go.mod
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build cmd/main.go